#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/communitylogin
#    username: root
#    password: 
#   
#  jpa: 
#    hibernate.ddl-auto: create
#    generate-ddl: true
#    show-sql: true
# 
#server:
#  port: 8082